### get all
GET http://localhost:4000/api/users/

### get by phone number
GET http://localhost:4000/api/users/1111111


### add user
POST http://localhost:4000/api/users/create
Content-Type: application/json

{
    "firstName": "erez",
    "lastName": "mizrahi",
    "address": "rosh haayin",
    "phoneNumber": "1111111"
}



### delete user
DELETE http://localhost:4000/api/users/delete/4

### add user hobbies
POST http://localhost:4000/api/users/hobby
Content-Type: application/json

{
    "userId": 2,
    "hobby": "test"
}
